// Generated by go run tools/generate.go > zones.go
// DO NOT EDIT

package whois

var zones = map[string]string{
	"ac":                     "whois.nic.ac",                         // whois -h whois.iana.org ac
	"academy":                "whois.donuts.co",                      // whois -h whois.iana.org academy
	"accountants":            "whois.donuts.co",                      // whois -h whois.iana.org accountants
	"actor":                  "whois.unitedtld.com",                  // whois -h whois.iana.org actor
	"ad":                     "whois.ripe.net",                       // dig ad.whois-servers.net CNAME
	"ae":                     "whois.aeda.net.ae",                    // whois -h whois.iana.org ae
	"aero":                   "whois.aero",                           // whois -h whois.iana.org aero
	"af":                     "whois.nic.af",                         // whois -h whois.iana.org af
	"ag":                     "whois.nic.ag",                         // whois -h whois.iana.org ag
	"agency":                 "whois.donuts.co",                      // whois -h whois.iana.org agency
	"ai":                     "whois.ai",                             // whois -h whois.iana.org ai
	"airforce":               "whois.unitedtld.com",                  // whois -h whois.iana.org airforce
	"al":                     "whois.ai",                             // dig al.whois-servers.net CNAME
	"am":                     "whois.amnic.net",                      // whois -h whois.iana.org am
	"an":                     "",                                     //
	"ao":                     "",                                     //
	"aq":                     "",                                     //
	"ar":                     "nic.ar",                               // web (CAPTCHA)
	"archi":                  "whois.ksregistry.net",                 // whois -h whois.iana.org archi
	"arpa":                   "whois.iana.org",                       // whois -h whois.iana.org arpa
	"as":                     "whois.nic.as",                         // whois -h whois.iana.org as
	"asia":                   "whois.nic.asia",                       // whois -h whois.iana.org asia
	"associates":             "whois.donuts.co",                      // whois -h whois.iana.org associates
	"at":                     "whois.nic.at",                         // whois -h whois.iana.org at
	"au":                     "whois.audns.net.au",                   // whois -h whois.iana.org au
	"audio":                  "whois.uniregistry.net",                // whois -h whois.iana.org audio
	"autos":                  "whois.afilias-srs.net",                // whois -h whois.iana.org autos
	"aw":                     "whois.nic.aw",                         // whois -h whois.iana.org aw
	"ax":                     "whois.ax",                             // whois -h whois.iana.org ax
	"axa":                    "whois.nic.axa",                        // dig axa.whois-servers.net CNAME
	"az":                     "whois.ripe.net",                       // dig az.whois-servers.net CNAME
	"ba":                     "whois.ripe.net",                       // dig ba.whois-servers.net CNAME
	"bar":                    "whois.nic.bar",                        // whois -h whois.iana.org bar
	"bargains":               "whois.donuts.co",                      // whois -h whois.iana.org bargains
	"bayern":                 "whois-dub.mm-registry.com",            // whois -h whois.iana.org bayern
	"bb":                     "",                                     //
	"bd":                     "www.whois.com.bd",                     // web
	"be":                     "whois.dns.be",                         // whois -h whois.iana.org be
	"beer":                   "whois-dub.mm-registry.com",            // whois -h whois.iana.org beer
	"berlin":                 "whois.nic.berlin",                     // whois -h whois.iana.org berlin
	"best":                   "whois.nic.best",                       // whois -h whois.iana.org best
	"bf":                     "",                                     //
	"bg":                     "whois.register.bg",                    // whois -h whois.iana.org bg
	"bh":                     "",                                     //
	"bi":                     "whois1.nic.bi",                        // whois -h whois.iana.org bi
	"bid":                    "whois.nic.bid",                        // dig bid.whois-servers.net CNAME
	"bike":                   "whois.donuts.co",                      // whois -h whois.iana.org bike
	"biz":                    "whois.biz",                            // whois -h whois.iana.org biz
	"bj":                     "whois.nic.bj",                         // whois -h whois.iana.org bj
	"black":                  "whois.afilias.net",                    // whois -h whois.iana.org black
	"blackfriday":            "whois.uniregistry.net",                // whois -h whois.iana.org blackfriday
	"blue":                   "whois.afilias.net",                    // whois -h whois.iana.org blue
	"bm":                     "www.bermudanic.bm",                    // web (POST)
	"bn":                     "whois.bn",                             // whois -h whois.iana.org bn
	"bo":                     "whois.nic.bo",                         // whois -h whois.iana.org bo
	"boutique":               "whois.donuts.co",                      // whois -h whois.iana.org boutique
	"br":                     "whois.registro.br",                    // whois -h whois.iana.org br
	"bs":                     "www.register.bs",                      // web
	"bt":                     "www.nic.bt",                           // web (POST)
	"build":                  "whois.nic.build",                      // whois -h whois.iana.org build
	"builders":               "whois.donuts.co",                      // whois -h whois.iana.org builders
	"buzz":                   "whois.nic.buzz",                       // dig buzz.whois-servers.net CNAME
	"bv":                     "whois.norid.no",                       // http://www.norid.no/navnepolitikk.en.html#link1
	"bw":                     "whois.nic.net.bw",                     // whois -h whois.iana.org bw
	"by":                     "whois.cctld.by",                       // whois -h whois.iana.org by
	"bz":                     "bzwhois.verisign-grs.com",             // dig bz.whois-servers.net CNAME
	"ca":                     "whois.cira.ca",                        // whois -h whois.iana.org ca
	"cab":                    "whois.donuts.co",                      // whois -h whois.iana.org cab
	"camera":                 "whois.donuts.co",                      // whois -h whois.iana.org camera
	"camp":                   "whois.donuts.co",                      // whois -h whois.iana.org camp
	"capital":                "whois.donuts.co",                      // whois -h whois.iana.org capital
	"cards":                  "whois.donuts.co",                      // whois -h whois.iana.org cards
	"care":                   "whois.donuts.co",                      // whois -h whois.iana.org care
	"career":                 "whois.nic.career",                     // dig career.whois-servers.net CNAME
	"careers":                "whois.donuts.co",                      // whois -h whois.iana.org careers
	"cash":                   "whois.donuts.co",                      // whois -h whois.iana.org cash
	"cat":                    "whois.cat",                            // whois -h whois.iana.org cat
	"catering":               "whois.donuts.co",                      // whois -h whois.iana.org catering
	"cc":                     "ccwhois.verisign-grs.com",             // whois -h whois.iana.org cc
	"cd":                     "whois.cd",                             // dig cd.whois-servers.net CNAME
	"center":                 "whois.donuts.co",                      // whois -h whois.iana.org center
	"ceo":                    "whois.nic.ceo",                        // whois -h whois.iana.org ceo
	"cf":                     "whois.dot.cf",                         // whois -h whois.iana.org cf
	"cg":                     "",                                     //
	"ch":                     "whois.nic.ch",                         // whois -h whois.iana.org ch
	"cheap":                  "whois.donuts.co",                      // whois -h whois.iana.org cheap
	"christmas":              "whois.uniregistry.net",                // whois -h whois.iana.org christmas
	"church":                 "whois.donuts.co",                      // whois -h whois.iana.org church
	"ci":                     "whois.nic.ci",                         // whois -h whois.iana.org ci
	"citic":                  "whois.nic.citic",                      // dig citic.whois-servers.net CNAME
	"ck":                     "whois.ck-nic.org.ck",                  // dig ck.whois-servers.net CNAME
	"cl":                     "whois.nic.cl",                         // whois -h whois.iana.org cl
	"claims":                 "whois.donuts.co",                      // whois -h whois.iana.org claims
	"cleaning":               "whois.donuts.co",                      // whois -h whois.iana.org cleaning
	"clinic":                 "whois.donuts.co",                      // whois -h whois.iana.org clinic
	"clothing":               "whois.donuts.co",                      // whois -h whois.iana.org clothing
	"club":                   "whois.nic.club",                       // whois -h whois.iana.org club
	"cm":                     "antic.cm",                             // web (sessioned)
	"cn":                     "whois.cnnic.cn",                       // whois -h whois.iana.org cn
	"co":                     "whois.nic.co",                         // whois -h whois.iana.org co
	"codes":                  "whois.donuts.co",                      // whois -h whois.iana.org codes
	"coffee":                 "whois.donuts.co",                      // whois -h whois.iana.org coffee
	"college":                "whois.centralnic.com",                 // whois -h whois.iana.org college
	"cologne":                "whois-fe1.pdt.cologne.tango.knipp.de", // whois -h whois.iana.org cologne
	"com":                    "whois.verisign-grs.com",               // whois -h whois.iana.org com
	"community":              "whois.donuts.co",                      // whois -h whois.iana.org community
	"company":                "whois.donuts.co",                      // whois -h whois.iana.org company
	"computer":               "whois.donuts.co",                      // whois -h whois.iana.org computer
	"condos":                 "whois.donuts.co",                      // whois -h whois.iana.org condos
	"construction":           "whois.donuts.co",                      // whois -h whois.iana.org construction
	"consulting":             "whois.unitedtld.com",                  // whois -h whois.iana.org consulting
	"contractors":            "whois.donuts.co",                      // whois -h whois.iana.org contractors
	"cooking":                "whois-dub.mm-registry.com",            // whois -h whois.iana.org cooking
	"cool":                   "whois.donuts.co",                      // whois -h whois.iana.org cool
	"coop":                   "whois.nic.coop",                       // whois -h whois.iana.org coop
	"country":                "whois-dub.mm-registry.com",            // whois -h whois.iana.org country
	"cr":                     "www.nic.cr",                           // web (CAPTCHA)
	"credit":                 "whois.donuts.co",                      // whois -h whois.iana.org credit
	"creditcard":             "whois.donuts.co",                      // whois -h whois.iana.org creditcard
	"cruises":                "whois.donuts.co",                      // whois -h whois.iana.org cruises
	"cu":                     "www.nic.cu",                           // web
	"cv":                     "www.dns.cv",                           // web
	"cw":                     "",                                     //
	"cx":                     "whois.nic.cx",                         // whois -h whois.iana.org cx
	"cy":                     "whois.ripe.net",                       // dig cy.whois-servers.net CNAME
	"cz":                     "whois.nic.cz",                         // whois -h whois.iana.org cz
	"dance":                  "whois.unitedtld.com",                  // whois -h whois.iana.org dance
	"dating":                 "whois.donuts.co",                      // whois -h whois.iana.org dating
	"de":                     "whois.denic.de",                       // whois -h whois.iana.org de
	"democrat":               "whois.unitedtld.com",                  // whois -h whois.iana.org democrat
	"dental":                 "whois.donuts.co",                      // whois -h whois.iana.org dental
	"desi":                   "whois.ksregistry.net",                 // whois -h whois.iana.org desi
	"diamonds":               "whois.donuts.co",                      // whois -h whois.iana.org diamonds
	"digital":                "whois.donuts.co",                      // whois -h whois.iana.org digital
	"directory":              "whois.donuts.co",                      // whois -h whois.iana.org directory
	"discount":               "whois.donuts.co",                      // whois -h whois.iana.org discount
	"dj":                     "www.dj",                               // web
	"dk":                     "whois.dk-hostmaster.dk",               // whois -h whois.iana.org dk
	"dm":                     "whois.nic.dm",                         // whois -h whois.iana.org dm
	"dnp":                    "whois.nic.dnp",                        // dig dnp.whois-servers.net CNAME
	"do":                     "ns.nic.do",                            // dig do.whois-servers.net CNAME
	"domains":                "whois.donuts.co",                      // whois -h whois.iana.org domains
	"dz":                     "whois.nic.dz",                         // whois -h whois.iana.org dz
	"ec":                     "whois.nic.ec",                         // whois -h whois.iana.org ec
	"edu":                    "whois.educause.edu",                   // whois -h whois.iana.org edu
	"education":              "whois.donuts.co",                      // whois -h whois.iana.org education
	"ee":                     "whois.tld.ee",                         // whois -h whois.iana.org ee
	"eg":                     "whois.ripe.net",                       // dig eg.whois-servers.net CNAME
	"email":                  "whois.donuts.co",                      // whois -h whois.iana.org email
	"engineering":            "whois.donuts.co",                      // whois -h whois.iana.org engineering
	"enterprises":            "whois.donuts.co",                      // whois -h whois.iana.org enterprises
	"equipment":              "whois.donuts.co",                      // whois -h whois.iana.org equipment
	"er":                     "",                                     //
	"es":                     "whois.nic.es",                         // whois -h whois.iana.org es
	"estate":                 "whois.donuts.co",                      // whois -h whois.iana.org estate
	"et":                     "",                                     //
	"eu":                     "whois.eu",                             // whois -h whois.iana.org eu
	"eus":                    "whois.eus.coreregistry.net",           // whois -h whois.iana.org eus
	"events":                 "whois.donuts.co",                      // whois -h whois.iana.org events
	"exchange":               "whois.donuts.co",                      // whois -h whois.iana.org exchange
	"expert":                 "whois.donuts.co",                      // whois -h whois.iana.org expert
	"exposed":                "whois.donuts.co",                      // whois -h whois.iana.org exposed
	"fail":                   "whois.donuts.co",                      // whois -h whois.iana.org fail
	"farm":                   "whois.donuts.co",                      // whois -h whois.iana.org farm
	"feedback":               "whois.centralnic.com",                 // whois -h whois.iana.org feedback
	"fi":                     "whois.fi",                             // whois -h whois.iana.org fi
	"finance":                "whois.donuts.co",                      // whois -h whois.iana.org finance
	"financial":              "whois.donuts.co",                      // whois -h whois.iana.org financial
	"fish":                   "whois.donuts.co",                      // whois -h whois.iana.org fish
	"fishing":                "whois-dub.mm-registry.com",            // whois -h whois.iana.org fishing
	"fitness":                "whois.donuts.co",                      // whois -h whois.iana.org fitness
	"fj":                     "domains.fj",                           // web
	"fk":                     "whois.marcaria.com",                   // web
	"flights":                "whois.donuts.co",                      // whois -h whois.iana.org flights
	"florist":                "whois.donuts.co",                      // whois -h whois.iana.org florist
	"fm":                     "whois.nic.fm",                         // dig fm.whois-servers.net CNAME
	"fo":                     "whois.nic.fo",                         // whois -h whois.iana.org fo
	"foo":                    "domain-registry-whois.l.google.com",   // whois -h whois.iana.org foo
	"foundation":             "whois.donuts.co",                      // whois -h whois.iana.org foundation
	"fr":                     "whois.nic.fr",                         // whois -h whois.iana.org fr
	"frogans":                "whois-frogans.nic.fr",                 // whois -h whois.iana.org frogans
	"fund":                   "whois.donuts.co",                      // whois -h whois.iana.org fund
	"furniture":              "whois.donuts.co",                      // whois -h whois.iana.org furniture
	"futbol":                 "whois.unitedtld.com",                  // whois -h whois.iana.org futbol
	"ga":                     "whois.dot.ga",                         // dig ga.whois-servers.net CNAME
	"gal":                    "whois.gal.coreregistry.net",           // whois -h whois.iana.org gal
	"gallery":                "whois.donuts.co",                      // whois -h whois.iana.org gallery
	"gb":                     "whois.ripe.net",                       // dig gb.whois-servers.net CNAME
	"gd":                     "whois.nic.gd",                         // whois -h whois.iana.org gd
	"ge":                     "whois.ripe.net",                       // dig ge.whois-servers.net CNAME
	"gf":                     "www.dom-enic.com",                     // web (POST)
	"gg":                     "whois.gg",                             // whois -h whois.iana.org gg
	"gh":                     "",                                     //
	"gi":                     "whois2.afilias-grs.net",               // whois -h whois.iana.org gi
	"gift":                   "whois.uniregistry.net",                // whois -h whois.iana.org gift
	"gl":                     "whois.nic.gl",                         // whois -h whois.iana.org gl
	"glass":                  "whois.donuts.co",                      // whois -h whois.iana.org glass
	"globo":                  "whois.gtlds.nic.br",                   // whois -h whois.iana.org globo
	"gm":                     "whois.ripe.net",                       // dig gm.whois-servers.net CNAME
	"gmo":                    "whois.gmoregistry.net",                // http://en.wikipedia.org/wiki/.gmo
	"gn":                     "",                                     //
	"gop":                    "whois-cl01.mm-registry.com",           // whois -h whois.iana.org gop
	"gov":                    "whois.dotgov.gov",                     // whois -h whois.iana.org gov
	"gp":                     "www.dom-enic.com",                     // web (POST)
	"gq":                     "",                                     //
	"gr":                     "whois.ripe.net",                       // dig gr.whois-servers.net CNAME
	"graphics":               "whois.donuts.co",                      // whois -h whois.iana.org graphics
	"gratis":                 "whois.donuts.co",                      // whois -h whois.iana.org gratis
	"gripe":                  "whois.donuts.co",                      // whois -h whois.iana.org gripe
	"gs":                     "whois.nic.gs",                         // whois -h whois.iana.org gs
	"gt":                     "www.gt",                               // web
	"gu":                     "",                                     //
	"guide":                  "whois.donuts.co",                      // whois -h whois.iana.org guide
	"guitars":                "whois.uniregistry.net",                // whois -h whois.iana.org guitars
	"guru":                   "whois.donuts.co",                      // whois -h whois.iana.org guru
	"gw":                     "",                                     //
	"gy":                     "whois.registry.gy",                    // whois -h whois.iana.org gy
	"haus":                   "whois.unitedtld.com",                  // whois -h whois.iana.org haus
	"hiphop":                 "whois.uniregistry.net",                // whois -h whois.iana.org hiphop
	"hk":                     "whois.hkirc.hk",                       // whois -h whois.iana.org hk
	"hm":                     "webhost1.capital.hm",                  // dig hm.whois-servers.net CNAME
	"hn":                     "whois.nic.hn",                         // whois -h whois.iana.org hn
	"holdings":               "whois.donuts.co",                      // whois -h whois.iana.org holdings
	"holiday":                "whois.donuts.co",                      // whois -h whois.iana.org holiday
	"homes":                  "whois.afilias-srs.net",                // whois -h whois.iana.org homes
	"horse":                  "whois-dub.mm-registry.com",            // whois -h whois.iana.org horse
	"house":                  "whois.donuts.co",                      // whois -h whois.iana.org house
	"hr":                     "whois.dns.hr",                         // whois -h whois.iana.org hr
	"ht":                     "whois.nic.ht",                         // whois -h whois.iana.org ht
	"hu":                     "whois.nic.hu",                         // whois -h whois.iana.org hu
	"id":                     "whois.pandi.or.id",                    // whois -h whois.iana.org id
	"ie":                     "whois.domainregistry.ie",              // whois -h whois.iana.org ie
	"il":                     "whois.isoc.org.il",                    // whois -h whois.iana.org il
	"im":                     "whois.nic.im",                         // whois -h whois.iana.org im
	"immobilien":             "whois.unitedtld.com",                  // whois -h whois.iana.org immobilien
	"in":                     "whois.inregistry.net",                 // whois -h whois.iana.org in
	"industries":             "whois.donuts.co",                      // whois -h whois.iana.org industries
	"info":                   "whois.afilias.net",                    // whois -h whois.iana.org info
	"ink":                    "whois.centralnic.com",                 // whois -h whois.iana.org ink
	"institute":              "whois.donuts.co",                      // whois -h whois.iana.org institute
	"insure":                 "whois.donuts.co",                      // whois -h whois.iana.org insure
	"int":                    "whois.iana.org",                       // whois -h whois.iana.org int
	"international":          "whois.donuts.co",                      // whois -h whois.iana.org international
	"investments":            "whois.donuts.co",                      // whois -h whois.iana.org investments
	"io":                     "whois.nic.io",                         // whois -h whois.iana.org io
	"iq":                     "whois.cmc.iq",                         // whois -h whois.iana.org iq
	"ir":                     "whois.nic.ir",                         // whois -h whois.iana.org ir
	"is":                     "whois.isnic.is",                       // whois -h whois.iana.org is
	"it":                     "whois.nic.it",                         // whois -h whois.iana.org it
	"je":                     "whois.je",                             // whois -h whois.iana.org je
	"jetzt":                  "whois.nic.jetzt",                      // dig jetzt.whois-servers.net CNAME
	"jm":                     "",                                     //
	"jo":                     "whois.ripe.net",                       // dig jo.whois-servers.net CNAME
	"jobs":                   "jobswhois.verisign-grs.com",           // whois -h whois.iana.org jobs
	"jp":                     "whois.jprs.jp",                        // whois -h whois.iana.org jp
	"juegos":                 "whois.uniregistry.net",                // whois -h whois.iana.org juegos
	"kaufen":                 "whois.unitedtld.com",                  // whois -h whois.iana.org kaufen
	"ke":                     "whois.kenic.or.ke",                    // whois -h whois.iana.org ke
	"kg":                     "whois.domain.kg",                      // whois -h whois.iana.org kg
	"kh":                     "",                                     //
	"ki":                     "whois.nic.ki",                         // whois -h whois.iana.org ki
	"kim":                    "whois.afilias.net",                    // whois -h whois.iana.org kim
	"kitchen":                "whois.donuts.co",                      // whois -h whois.iana.org kitchen
	"kiwi":                   "whois.dot-kiwi.com",                   // whois -h whois.iana.org kiwi
	"km":                     "",                                     //
	"kn":                     "",                                     //
	"koeln":                  "whois-fe1.pdt.koeln.tango.knipp.de",   // whois -h whois.iana.org koeln
	"kp":                     "",                                     //
	"kr":                     "whois.kr",                             // whois -h whois.iana.org kr
	"kred":                   "whois.nic.kred",                       // dig kred.whois-servers.net CNAME
	"kw":                     "www.kw",                               // web (POST)
	"ky":                     "kynseweb.messagesecure.com",           // web (POST)
	"kz":                     "whois.nic.kz",                         // whois -h whois.iana.org kz
	"la":                     "whois.nic.la",                         // whois -h whois.iana.org la
	"land":                   "whois.donuts.co",                      // whois -h whois.iana.org land
	"lb":                     "www.aub.edu.lb",                       // web
	"lc":                     "www.nic.lc",                           // web (POST)
	"lease":                  "whois.donuts.co",                      // whois -h whois.iana.org lease
	"li":                     "whois.nic.li",                         // whois -h whois.iana.org li
	"life":                   "whois.donuts.co",                      // whois -h whois.iana.org life
	"lighting":               "whois.donuts.co",                      // whois -h whois.iana.org lighting
	"limited":                "whois.donuts.co",                      // whois -h whois.iana.org limited
	"limo":                   "whois.donuts.co",                      // whois -h whois.iana.org limo
	"link":                   "whois.uniregistry.net",                // whois -h whois.iana.org link
	"lk":                     "arisen.nic.lk",                        // dig lk.whois-servers.net CNAME
	"loans":                  "whois.donuts.co",                      // whois -h whois.iana.org loans
	"london":                 "whois-lon.mm-registry.com",            // whois -h whois.iana.org london
	"lr":                     "",                                     //
	"ls":                     "www.co.ls",                            // web
	"lt":                     "whois.domreg.lt",                      // whois -h whois.iana.org lt
	"lu":                     "whois.dns.lu",                         // whois -h whois.iana.org lu
	"luxe":                   "whois-dub.mm-registry.com",            // whois -h whois.iana.org luxe
	"luxury":                 "whois.nic.luxury",                     // whois -h whois.iana.org luxury
	"lv":                     "whois.nic.lv",                         // whois -h whois.iana.org lv
	"ly":                     "whois.nic.ly",                         // whois -h whois.iana.org ly
	"ma":                     "whois.iam.net.ma",                     // whois -h whois.iana.org ma
	"maison":                 "whois.donuts.co",                      // whois -h whois.iana.org maison
	"management":             "whois.donuts.co",                      // whois -h whois.iana.org management
	"mango":                  "whois.mango.coreregistry.net",         // whois -h whois.iana.org mango
	"marketing":              "whois.donuts.co",                      // whois -h whois.iana.org marketing
	"mc":                     "whois.ripe.net",                       // dig mc.whois-servers.net CNAME
	"md":                     "whois.nic.md",                         // whois -h whois.iana.org md
	"me":                     "whois.nic.me",                         // whois -h whois.iana.org me
	"media":                  "whois.donuts.co",                      // whois -h whois.iana.org media
	"meet":                   "whois.afilias.net",                    // whois -h whois.iana.org meet
	"menu":                   "whois.nic.menu",                       // whois -h whois.iana.org menu
	"mg":                     "whois.nic.mg",                         // whois -h whois.iana.org mg
	"mh":                     "",                                     //
	"miami":                  "whois-dub.mm-registry.com",            // whois -h whois.iana.org miami
	"mil":                    "is-1.nic.mil",                         // dig mil.whois-servers.net CNAME
	"mk":                     "whois.marnet.mk",                      // whois -h whois.iana.org mk
	"ml":                     "whois.dot.ml",                         // whois -h whois.iana.org ml
	"mm":                     "whois.nic.mm",                         // dig mm.whois-servers.net CNAME
	"mn":                     "whois.nic.mn",                         // whois -h whois.iana.org mn
	"mo":                     "whois.monic.mo",                       // whois -h whois.iana.org mo
	"mobi":                   "whois.dotmobiregistry.net",            // whois -h whois.iana.org mobi
	"moda":                   "whois.unitedtld.com",                  // whois -h whois.iana.org moda
	"moe":                    "whois.nic.moe",                        // dig moe.whois-servers.net CNAME
	"monash":                 "whois.nic.monash",                     // whois -h whois.iana.org monash
	"moscow":                 "whois.nic.moscow",                     // whois -h whois.iana.org moscow
	"motorcycles":            "whois.afilias-srs.net",                // whois -h whois.iana.org motorcycles
	"mp":                     "whois.nic.mp",                         // whois -h whois.iana.org mp
	"mq":                     "www.dom-enic.com",                     // web (POST)
	"mr":                     "",                                     //
	"ms":                     "whois.nic.ms",                         // whois -h whois.iana.org ms
	"mt":                     "whois.ripe.net",                       // dig mt.whois-servers.net CNAME
	"mu":                     "whois.nic.mu",                         // whois -h whois.iana.org mu
	"museum":                 "whois.museum",                         // whois -h whois.iana.org museum
	"mv":                     "",                                     //
	"mw":                     "www.registrar.mw",                     // web
	"mx":                     "whois.mx",                             // whois -h whois.iana.org mx
	"my":                     "whois.domainregistry.my",              // whois -h whois.iana.org my
	"mz":                     "www.domains.co.mz",                    // web (CAPTCHA)
	"na":                     "whois.na-nic.com.na",                  // whois -h whois.iana.org na
	"nagoya":                 "whois.nic.nagoya",                     // dig nagoya.whois-servers.net CNAME
	"name":                   "whois.nic.name",                       // whois -h whois.iana.org name
	"nc":                     "whois.nc",                             // whois -h whois.iana.org nc
	"ne":                     "",                                     //
	"net":                    "whois.verisign-grs.com",               // whois -h whois.iana.org net
	"neustar":                "whois.nic.neustar",                    // dig neustar.whois-servers.net CNAME
	"nf":                     "whois.nic.nf",                         // whois -h whois.iana.org nf
	"ng":                     "whois.nic.net.ng",                     // whois -h whois.iana.org ng
	"ni":                     "www.nic.ni",                           // web (POST AJAX)
	"ninja":                  "whois.unitedtld.com",                  // whois -h whois.iana.org ninja
	"nl":                     "whois.domain-registry.nl",             // whois -h whois.iana.org nl
	"no":                     "whois.norid.no",                       // whois -h whois.iana.org no
	"np":                     "register.mos.com.np",                  // web (POST)
	"nr":                     "cenpac.net.nr",                        // http://cenpac.net.nr/dns/
	"nu":                     "whois.iis.nu",                         // whois -h whois.iana.org nu
	"nyc":                    "whois.nic.nyc",                        // dig nyc.whois-servers.net CNAME
	"nz":                     "whois.srs.net.nz",                     // whois -h whois.iana.org nz
	"okinawa":                "whois.nic.okinawa",                    // dig okinawa.whois-servers.net CNAME
	"om":                     "whois.registry.om",                    // whois -h whois.iana.org om
	"onl":                    "whois.afilias-srs.net",                // whois -h whois.iana.org onl
	"org":                    "whois.pir.org",                        // whois -h whois.iana.org org
	"pa":                     "www.nic.pa",                           // web
	"paris":                  "whois-paris.nic.fr",                   // whois -h whois.iana.org paris
	"partners":               "whois.donuts.co",                      // whois -h whois.iana.org partners
	"parts":                  "whois.donuts.co",                      // whois -h whois.iana.org parts
	"pe":                     "kero.yachay.pe",                       // whois -h whois.iana.org pe
	"pf":                     "whois.registry.pf",                    // whois -h whois.iana.org pf
	"pg":                     "",                                     //
	"ph":                     "www.dot.ph",                           // web (CAPTCHA)
	"photo":                  "whois.uniregistry.net",                // whois -h whois.iana.org photo
	"photography":            "whois.donuts.co",                      // whois -h whois.iana.org photography
	"photos":                 "whois.donuts.co",                      // whois -h whois.iana.org photos
	"pics":                   "whois.uniregistry.net",                // whois -h whois.iana.org pics
	"pictures":               "whois.donuts.co",                      // whois -h whois.iana.org pictures
	"pink":                   "whois.afilias.net",                    // whois -h whois.iana.org pink
	"pk":                     "pk6.pknic.net.pk",                     // web
	"pl":                     "whois.dns.pl",                         // whois -h whois.iana.org pl
	"plumbing":               "whois.donuts.co",                      // whois -h whois.iana.org plumbing
	"pm":                     "whois.nic.pm",                         // whois -h whois.iana.org pm
	"pn":                     "www.government.pn",                    // web (POST)
	"post":                   "whois.dotpostregistry.net",            // whois -h whois.iana.org post
	"pr":                     "whois.nic.pr",                         // whois -h whois.iana.org pr
	"pro":                    "whois.dotproregistry.net",             // whois -h whois.iana.org pro
	"productions":            "whois.donuts.co",                      // whois -h whois.iana.org productions
	"properties":             "whois.donuts.co",                      // whois -h whois.iana.org properties
	"ps":                     "whois.pnina.ps",                       // dig ps.whois-servers.net CNAME
	"pt":                     "whois.dns.pt",                         // whois -h whois.iana.org pt
	"pub":                    "whois.unitedtld.com",                  // whois -h whois.iana.org pub
	"pw":                     "whois.nic.pw",                         // whois -h whois.iana.org pw
	"py":                     "www.nic.py",                           // web (POST)
	"qa":                     "whois.registry.qa",                    // whois -h whois.iana.org qa
	"qpon":                   "whois.nic.qpon",                       // dig qpon.whois-servers.net CNAME
	"quebec":                 "whois.quebec.rs.corenic.net",          // whois -h whois.iana.org quebec
	"re":                     "whois.nic.re",                         // whois -h whois.iana.org re
	"recipes":                "whois.donuts.co",                      // whois -h whois.iana.org recipes
	"red":                    "whois.afilias.net",                    // whois -h whois.iana.org red
	"reise":                  "whois.reise.tld-box.at",               // whois -h whois.iana.org reise
	"reisen":                 "whois.donuts.co",                      // whois -h whois.iana.org reisen
	"ren":                    "whois.nic.ren",                        // dig ren.whois-servers.net CNAME
	"rentals":                "whois.donuts.co",                      // whois -h whois.iana.org rentals
	"repair":                 "whois.donuts.co",                      // whois -h whois.iana.org repair
	"report":                 "whois.donuts.co",                      // whois -h whois.iana.org report
	"rest":                   "whois.centralnic.com",                 // whois -h whois.iana.org rest
	"reviews":                "whois.unitedtld.com",                  // whois -h whois.iana.org reviews
	"rich":                   "whois.afilias-srs.net",                // whois -h whois.iana.org rich
	"rio":                    "whois.gtlds.nic.br",                   // whois -h whois.iana.org rio
	"ro":                     "whois.rotld.ro",                       // whois -h whois.iana.org ro
	"rocks":                  "whois.unitedtld.com",                  // whois -h whois.iana.org rocks
	"rodeo":                  "whois-dub.mm-registry.com",            // whois -h whois.iana.org rodeo
	"rs":                     "whois.rnids.rs",                       // whois -h whois.iana.org rs
	"ru":                     "whois.tcinet.ru",                      // whois -h whois.iana.org ru
	"ruhr":                   "whois.nic.ruhr",                       // whois -h whois.iana.org ruhr
	"rw":                     "whois.ricta.org.rw",                   // web
	"ryukyu":                 "whois.nic.ryukyu",                     // dig ryukyu.whois-servers.net CNAME
	"sa":                     "whois.nic.net.sa",                     // whois -h whois.iana.org sa
	"saarland":               "whois.ksregistry.net",                 // whois -h whois.iana.org saarland
	"sb":                     "whois.nic.net.sb",                     // whois -h whois.iana.org sb
	"sc":                     "whois2.afilias-grs.net",               // whois -h whois.iana.org sc
	"schule":                 "whois.donuts.co",                      // whois -h whois.iana.org schule
	"sd":                     "",                                     //
	"se":                     "whois.iis.se",                         // whois -h whois.iana.org se
	"services":               "whois.donuts.co",                      // whois -h whois.iana.org services
	"sexy":                   "whois.uniregistry.net",                // whois -h whois.iana.org sexy
	"sg":                     "whois.sgnic.sg",                       // whois -h whois.iana.org sg
	"sh":                     "whois.nic.sh",                         // whois -h whois.iana.org sh
	"shiksha":                "whois.afilias.net",                    // whois -h whois.iana.org shiksha
	"shoes":                  "whois.donuts.co",                      // whois -h whois.iana.org shoes
	"si":                     "whois.arnes.si",                       // whois -h whois.iana.org si
	"singles":                "whois.donuts.co",                      // whois -h whois.iana.org singles
	"sj":                     "whois.norid.no",                       // http://www.norid.no/navnepolitikk.en.html#link1
	"sk":                     "whois.sk-nic.sk",                      // whois -h whois.iana.org sk
	"sl":                     "www.nic.sl",                           // web
	"sm":                     "whois.nic.sm",                         // whois -h whois.iana.org sm
	"sn":                     "whois.nic.sn",                         // whois -h whois.iana.org sn
	"so":                     "whois.nic.so",                         // whois -h whois.iana.org so
	"social":                 "whois.unitedtld.com",                  // whois -h whois.iana.org social
	"sohu":                   "whois.nic.sohu",                       // dig sohu.whois-servers.net CNAME
	"solar":                  "whois.donuts.co",                      // whois -h whois.iana.org solar
	"solutions":              "whois.donuts.co",                      // whois -h whois.iana.org solutions
	"soy":                    "domain-registry-whois.l.google.com",   // whois -h whois.iana.org soy
	"sr":                     "www.register.sr",                      // web (CAPTCHA)
	"st":                     "whois.nic.st",                         // whois -h whois.iana.org st
	"su":                     "whois.tcinet.ru",                      // whois -h whois.iana.org su
	"supplies":               "whois.donuts.co",                      // whois -h whois.iana.org supplies
	"supply":                 "whois.donuts.co",                      // whois -h whois.iana.org supply
	"support":                "whois.donuts.co",                      // whois -h whois.iana.org support
	"surgery":                "whois.donuts.co",                      // whois -h whois.iana.org surgery
	"sv":                     "",                                     //
	"sx":                     "whois.sx",                             // whois -h whois.iana.org sx
	"sy":                     "whois.tld.sy",                         // whois -h whois.iana.org sy
	"systems":                "whois.donuts.co",                      // whois -h whois.iana.org systems
	"sz":                     "",                                     //
	"tattoo":                 "whois.uniregistry.net",                // whois -h whois.iana.org tattoo
	"tax":                    "whois.donuts.co",                      // whois -h whois.iana.org tax
	"tc":                     "whois.meridiantld.net",                // whois -h whois.iana.org tc
	"td":                     "",                                     //
	"technology":             "whois.donuts.co",                      // whois -h whois.iana.org technology
	"tel":                    "whois.nic.tel",                        // whois -h whois.iana.org tel
	"tf":                     "whois.nic.tf",                         // whois -h whois.iana.org tf
	"tg":                     "www.netmaster.tg",                     // web
	"th":                     "whois.thnic.co.th",                    // whois -h whois.iana.org th
	"tienda":                 "whois.donuts.co",                      // whois -h whois.iana.org tienda
	"tips":                   "whois.donuts.co",                      // whois -h whois.iana.org tips
	"tj":                     "www.nic.tj",                           // web
	"tk":                     "whois.dot.tk",                         // whois -h whois.iana.org tk
	"tl":                     "whois.nic.tl",                         // whois -h whois.iana.org tl
	"tm":                     "whois.nic.tm",                         // whois -h whois.iana.org tm
	"tn":                     "whois.ati.tn",                         // whois -h whois.iana.org tn
	"to":                     "whois.tonic.to",                       // whois -h whois.iana.org to
	"today":                  "whois.donuts.co",                      // whois -h whois.iana.org today
	"tokyo":                  "whois.nic.tokyo",                      // dig tokyo.whois-servers.net CNAME
	"tools":                  "whois.donuts.co",                      // whois -h whois.iana.org tools
	"town":                   "whois.donuts.co",                      // whois -h whois.iana.org town
	"toys":                   "whois.donuts.co",                      // whois -h whois.iana.org toys
	"tp":                     "",                                     //
	"tr":                     "whois.nic.tr",                         // whois -h whois.iana.org tr
	"trade":                  "whois.nic.trade",                      // dig trade.whois-servers.net CNAME
	"training":               "whois.donuts.co",                      // whois -h whois.iana.org training
	"travel":                 "whois.nic.travel",                     // whois -h whois.iana.org travel
	"tt":                     "www.nic.tt",                           // web
	"tv":                     "tvwhois.verisign-grs.com",             // whois -h whois.iana.org tv
	"tw":                     "whois.twnic.net.tw",                   // whois -h whois.iana.org tw
	"tz":                     "whois.tznic.or.tz",                    // whois -h whois.iana.org tz
	"ua":                     "whois.ua",                             // whois -h whois.iana.org ua
	"ug":                     "whois.co.ug",                          // whois -h whois.iana.org ug
	"uk":                     "whois.nic.uk",                         // whois -h whois.iana.org uk
	"university":             "whois.donuts.co",                      // whois -h whois.iana.org university
	"uno":                    "whois.nic.uno",                        // dig uno.whois-servers.net CNAME
	"us":                     "whois.nic.us",                         // whois -h whois.iana.org us
	"uy":                     "whois.nic.org.uy",                     // whois -h whois.iana.org uy
	"uz":                     "whois.cctld.uz",                       // whois -h whois.iana.org uz
	"va":                     "whois.ripe.net",                       // dig va.whois-servers.net CNAME
	"vacations":              "whois.donuts.co",                      // whois -h whois.iana.org vacations
	"vc":                     "whois2.afilias-grs.net",               // whois -h whois.iana.org vc
	"ve":                     "whois.nic.ve",                         // whois -h whois.iana.org ve
	"vegas":                  "whois.afilias-srs.net",                // whois -h whois.iana.org vegas
	"ventures":               "whois.donuts.co",                      // whois -h whois.iana.org ventures
	"versicherung":           "whois.versicherung.tld-box.at",        // whois -h whois.iana.org versicherung
	"vg":                     "ccwhois.ksregistry.net",               // whois -h whois.iana.org vg
	"vi":                     "secure.nic.vi",                        // web (POST)
	"viajes":                 "whois.donuts.co",                      // whois -h whois.iana.org viajes
	"villas":                 "whois.donuts.co",                      // whois -h whois.iana.org villas
	"vision":                 "whois.donuts.co",                      // whois -h whois.iana.org vision
	"vn":                     "whois.vnnic.vn",                       // web
	"vodka":                  "whois-dub.mm-registry.com",            // whois -h whois.iana.org vodka
	"vote":                   "whois.afilias.net",                    // whois -h whois.iana.org vote
	"voting":                 "whois.voting.tld-box.at",              // whois -h whois.iana.org voting
	"voto":                   "whois.afilias.net",                    // whois -h whois.iana.org voto
	"voyage":                 "whois.donuts.co",                      // whois -h whois.iana.org voyage
	"vu":                     "vunic.vu",                             // whois -h whois.iana.org vu
	"wang":                   "whois.gtld.knet.cn",                   // whois -h whois.iana.org wang
	"watch":                  "whois.donuts.co",                      // whois -h whois.iana.org watch
	"webcam":                 "whois.nic.webcam",                     // dig webcam.whois-servers.net CNAME
	"wed":                    "whois.nic.wed",                        // whois -h whois.iana.org wed
	"wf":                     "whois.nic.wf",                         // whois -h whois.iana.org wf
	"wien":                   "whois.nic.wien",                       // whois -h whois.iana.org wien
	"wiki":                   "whois.nic.wiki",                       // whois -h whois.iana.org wiki
	"works":                  "whois.donuts.co",                      // whois -h whois.iana.org works
	"ws":                     "whois.website.ws",                     // whois -h whois.iana.org ws
	"wtc":                    "whois.nic.wtc",                        // whois -h whois.iana.org wtc
	"wtf":                    "whois.donuts.co",                      // whois -h whois.iana.org wtf
	"xn--3bst00m":            "whois.gtld.knet.cn",                   // whois -h whois.iana.org xn--3bst00m
	"xn--3ds443g":            "whois.afilias-srs.net",                // whois -h whois.iana.org xn--3ds443g
	"xn--3e0b707e":           "whois.kr",                             // whois -h whois.iana.org xn--3e0b707e
	"xn--45brj9c":            "",                                     //
	"xn--55qw42g":            "whois.conac.cn",                       // whois -h whois.iana.org xn--55qw42g
	"xn--55qx5d":             "whois.ngtld.cn",                       // whois -h whois.iana.org xn--55qx5d
	"xn--6frz82g":            "whois.afilias.net",                    // whois -h whois.iana.org xn--6frz82g
	"xn--6qq986b3xl":         "whois.gtld.knet.cn",                   // whois -h whois.iana.org xn--6qq986b3xl
	"xn--80adxhks":           "whois.nic.xn--80adxhks",               // whois -h whois.iana.org xn--80adxhks
	"xn--80ao21a":            "whois.nic.kz",                         // whois -h whois.iana.org xn--80ao21a
	"xn--80asehdb":           "whois.online.rs.corenic.net",          // whois -h whois.iana.org xn--80asehdb
	"xn--80aswg":             "whois.site.rs.corenic.net",            // whois -h whois.iana.org xn--80aswg
	"xn--90a3ac":             "whois.rnids.rs",                       // http://en.wikipedia.org/wiki/.xn--90a3ac
	"xn--c1avg":              "whois.publicinterestregistry.net",     // whois -h whois.iana.org xn--c1avg
	"xn--cg4bki":             "whois.kr",                             // whois -h whois.iana.org xn--cg4bki
	"xn--clchc0ea0b2g2a9gcd": "whois.sgnic.sg",                       // whois -h whois.iana.org xn--clchc0ea0b2g2a9gcd
	"xn--czr694b":            "",                                     //
	"xn--czru2d":             "whois.gtld.knet.cn",                   // whois -h whois.iana.org xn--czru2d
	"xn--d1acj3b":            "whois.nic.xn--d1acj3b",                // whois -h whois.iana.org xn--d1acj3b
	"xn--fiq228c5hs":         "whois.afilias-srs.net",                // whois -h whois.iana.org xn--fiq228c5hs
	"xn--fiq64b":             "whois.gtld.knet.cn",                   // whois -h whois.iana.org xn--fiq64b
	"xn--fiqs8s":             "cwhois.cnnic.cn",                      // whois -h whois.iana.org xn--fiqs8s
	"xn--fiqz9s":             "cwhois.cnnic.cn",                      // whois -h whois.iana.org xn--fiqz9s
	"xn--fpcrj9c3d":          "",                                     //
	"xn--fzc2c9e2c":          "whois.nic.lk",                         // http://www.iana.org/domains/root/db/.xn--fzc2c9e2c.html
	"xn--gecrj9c":            "",                                     //
	"xn--h2brj9c":            "",                                     //
	"xn--i1b6b1a6a2e":        "whois.publicinterestregistry.net",     // whois -h whois.iana.org xn--i1b6b1a6a2e
	"xn--io0a7i":             "whois.ngtld.cn",                       // whois -h whois.iana.org xn--io0a7i
	"xn--j1amh":              "whois.dotukr.com",                     // whois -h whois.iana.org xn--j1amh
	"xn--j6w193g":            "whois.hkirc.hk",                       // whois -h whois.iana.org xn--j6w193g
	"xn--kprw13d":            "whois.twnic.net.tw",                   // whois -h whois.iana.org xn--kprw13d
	"xn--kpry57d":            "whois.twnic.net.tw",                   // whois -h whois.iana.org xn--kpry57d
	"xn--l1acc":              "",                                     //
	"xn--lgbbat1ad8j":        "whois.nic.dz",                         // whois -h whois.iana.org xn--lgbbat1ad8j
	"xn--mgb9awbf":           "whois.registry.om",                    // whois -h whois.iana.org xn--mgb9awbf
	"xn--mgba3a4f16a":        "whois.nic.ir",                         // whois -h whois.iana.org xn--mgba3a4f16a
	"xn--mgbaam7a8h":         "whois.aeda.net.ae",                    // whois -h whois.iana.org xn--mgbaam7a8h
	"xn--mgbab2bd":           "whois.bazaar.coreregistry.net",        // whois -h whois.iana.org xn--mgbab2bd
	"xn--mgbayh7gpa":         "",                                     //
	"xn--mgbbh1a71e":         "",                                     //
	"xn--mgbc0a9azcg":        "whois.iam.net.ma",                     // Morocco
	"xn--mgberp4a5d4ar":      "whois.nic.net.sa",                     // whois -h whois.iana.org xn--mgberp4a5d4ar
	"xn--mgbx4cd0ab":         "whois.domainregistry.my",              // whois -h whois.iana.org xn--mgbx4cd0ab
	"xn--ngbc5azd":           "whois.nic.xn--ngbc5azd",               // whois -h whois.iana.org xn--ngbc5azd
	"xn--nqv7f":              "whois.publicinterestregistry.net",     // whois -h whois.iana.org xn--nqv7f
	"xn--nqv7fs00ema":        "whois.publicinterestregistry.net",     // whois -h whois.iana.org xn--nqv7fs00ema
	"xn--o3cw4h":             "whois.thnic.co.th",                    // whois -h whois.iana.org xn--o3cw4h
	"xn--ogbpf8fl":           "whois.tld.sy",                         // whois -h whois.iana.org xn--ogbpf8fl
	"xn--p1ai":               "whois.tcinet.ru",                      // whois -h whois.iana.org xn--p1ai
	"xn--pgbs0dh":            "whois.ati.tn",                         // Tunisia
	"xn--q9jyb4c":            "domain-registry-whois.l.google.com",   // whois -h whois.iana.org xn--q9jyb4c
	"xn--rhqv96g":            "whois.nic.xn--rhqv96g",                // China
	"xn--s9brj9c":            "",                                     //
	"xn--ses554g":            "whois.gtld.knet.cn",                   // China: whois -h whois.gtld.knet.cn nic.xn--ses554g
	"xn--unup4y":             "whois.donuts.co",                      // whois -h whois.iana.org xn--unup4y
	"xn--wgbh1c":             "",                                     //
	"xn--wgbl6a":             "whois.registry.qa",                    // whois -h whois.iana.org xn--wgbl6a
	"xn--xkc2al3hye2a":       "whois.nic.lk",                         // Sri Lanka
	"xn--xkc2dl3a5ee0h":      "",                                     //
	"xn--yfro4i67o":          "whois.sgnic.sg",                       // whois -h whois.iana.org xn--yfro4i67o
	"xn--ygbi2ammx":          "whois.pnina.ps",                       // whois -h whois.iana.org xn--ygbi2ammx
	"xn--zfr164b":            "whois.conac.cn",                       // whois -h whois.iana.org xn--zfr164b
	"xxx":                    "whois.nic.xxx",                        // whois -h whois.iana.org xxx
	"xyz":                    "whois.nic.xyz",                        // whois -h whois.iana.org xyz
	"yachts":                 "whois.afilias-srs.net",                // whois -h whois.iana.org yachts
	"ye":                     "",                                     //
	"yokohama":               "whois.nic.yokohama",                   // dig yokohama.whois-servers.net CNAME
	"yt":                     "whois.nic.yt",                         // whois -h whois.iana.org yt
	"za":                     "whois.registry.net.za",                // http://en.wikipedia.org/wiki/.za
	"zm":                     "whois.nic.zm",                         // whois -h whois.iana.org zm
	"zone":                   "whois.donuts.co",                      // whois -h whois.iana.org zone
	"zw":                     "www.zispa.org.zw",                     // web
}
