// Autogenerated 2014-05-02

package whois

import (
	"strings"
)

var zones = map[string]string{
	"com": "whois://whois.verisign-grs.com/={{query}}",
	"ga":  "whois.dot.ga",
	"nr":  "http://cenpac.net.nr/dns/whois.html?subdomain={{subdomain}}&tld=nr",
	"org": "whois.pir.org",
}
